### ISSUE TITLE
Should custom Slack emoji be included in this repository?

### ISSUE THREAD

**Issue by johnsyweb** [binaryberry/seal#23]
# Context

![slack 2015-08-20 09-08-33](https://cloud.githubusercontent.com/assets/39911/9372858/f204e5b0-4726-11e5-956f-dc7b87bd6a39.png)

# Recommendation

Create an `/emoji/` folder with images for each of the seals for new users to import to their Slack accounts.

**Comment by binaryberry** [comment]
Ah yes, excellent suggestion

**Comment by binaryberry** [comment]
Done with #25! Thanks again!
