### ISSUE TITLE
:happyseal: image is missing

### ISSUE THREAD

**Issue by stig** [binaryberry/seal#41]
Just had this message:

> Good morning team! It's a beautiful day! :happyseal: :happyseal: :happyseal:

The README only mentions:

> You should also set up the following custom emojis in Slack:
> 
> :informative_seal:
> :angrier_seal:
> :seal_of_approval:
>
> You can use the images in images/emojis that have the corresponding names.

and the images/emoji directory doesn't contain any happy seal images :-(

**Comment by stig** [comment]
PS: thank you for this project, it's helping us address many PRs that have fallen between the cracks :-)

**Comment by binaryberry** [comment]
Thanks for pointing it out, Stig, and glad you are finding the seal useful!
I've just merged a PR that adds the happy seal emoji to the emojis folder and readme instructions. It seems happy seals are bouncy creatures. 
Let me know if it doesn't work!
